### ISSUE TITLE
UNABLE TO USE NUMERIC VALUES IN API PATHS

### ISSUE THREAD

**Issue by jeffwecan** [gulducat/basic-api#5]
PLEASE TO BE FIXING THANK YOU SIR FOR YOUR GOOD WORK BUT IN TRUTH THIS PART DOES NOT WORK!!!

```
%▶ ./thinger.py                                                                                                                                                      
Traceback (most recent call last):
  File "/Users/jeffwecan/workspace/aguante/./thinger.py", line 21, in <module>
    thing = seatgeek_events[739515]
  File "/Users/jeffwecan/.virtualenvs/aguante/lib/python3.9/site-packages/basic_api/__init__.py", line 47, in __getattr__
    self._method = attr.lower()
AttributeError: 'int' object has no attribute 'lower'
```

**Comment by jeffwecan** [comment]
REPLICATION SCRIPT:

```python
#!/usr/bin/env python
import os
from pprint import pprint

from basic_api import BasicAPI
from requests.auth import HTTPBasicAuth

BASE_URL = "https://api.seatgeek.com/2/events"

if __name__ == "__main__":
    client_id = os.environ['SEATGEEK_CLIENT_ID']
    client_secret = os.environ['SEATGEEK_CLIENT_SECRET']

    seatgeek_auth = HTTPBasicAuth(client_id, client_secret)

    seatgeek_events = BasicAPI(
        base_url=BASE_URL,
        auth=seatgeek_auth,
    )
    thing = seatgeek_events[739515]
    pprint(thing)
    breakpoint()

```

**Comment by jeffwecan** [comment]
TURNS OUT I WAS MISSING A `.get`. THIS ISSUE CAN BE CONSIDERED RESOLVED. THANK YOU.

**Comment by jeffwecan** [comment]
ACTUALLY THERE IS A SIMILAR BUT DIFFERENT ISSUE:

```
%▶ ./thinger.py
Traceback (most recent call last):
  File "/Users/jeffwecan/workspace/aguante/./thinger.py", line 21, in <module>
    thing = seatgeek_events.get(739515)
  File "/Users/jeffwecan/.virtualenvs/aguante/lib/python3.9/site-packages/basic_api/__init__.py", line 62, in __call__
    url = '/'.join([
TypeError: can only concatenate str (not "int") to str
```

I"M GOING TO REPURPOSES THIS ISSUE FOR THIS NEWLY IDENTIFIED ISSUE. THANKS!!
